# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: config-pod
# spec:
#   containers:
#   - name: ngin
#     image: nginx
#     env:
#     - name: course
#       valueFrom:
#         configMapKeyRef:
#           name: course-config
#           key: course
#     - name: duration
#       valueFrom:
#         configMapKeyRef:
#           name: course-config
#           key: duration
---
apiVersion: v1
kind: Pod
metadata:
  name: config-pod
spec:
  containers:
  - name: ngin
    image: nginx
    envFrom:
      - configMapRef:
            name: course-config
    
    